In [1]:
#import pandas
import pandas as pd

In [2]:
# transformer le fichier .csv en DataFrame, séprarateur ; et décimal ,
df = pd.read_csv('country_gdp_per_capita.csv', sep=';', decimal=',')

In [ ]:
df_test = pd.read_csv('test.csv')

In [5]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,256,257,258,259,260,261,262,263,264,265
Country Name,Aruba,Africa Eastern and Southern,Afghanistan,Africa Western and Central,Angola,Albania,Andorra,Arab World,United Arab Emirates,Argentina,...,Virgin Islands (U.S.),Viet Nam,Vanuatu,World,Samoa,Kosovo,Yemen,South Africa,Zambia,Zimbabwe
Country Code,ABW,AFE,AFG,AFW,AGO,ALB,AND,ARB,ARE,ARG,...,VIR,VNM,VUT,WLD,WSM,XKX,Rep.,ZAF,ZMB,ZWE
Indicator Name,GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$),...,GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$),YEM,GDP per capita (current US$),GDP per capita (current US$),GDP per capita (current US$)
Indicator Code,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD
1960,NaN,"141,3859554","62,36937451","107,0537061",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"455,5986208",NaN,NaN,"NY,GDP,PCAP,CD","529,5619227","228,5673985","276,6433633"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019,31902.80982,1507.982881,497.741429,1812.446822,2191.347764,5396.214243,41328.61239,6504.789633,45376.17084,9963.674162,...,38633.52989,3491.09141,3076.589886,11338.15032,4308.300729,4416.029253,701.714869,6702.526617,1268.120941,1421.868596
2020,24008.12782,1355.805923,512.055098,1688.075575,1450.905112,5343.037704,37207.23887,5644.14257,37629.17417,8500.837939,...,39411.04525,3586.347176,2917.756849,10904.14761,4042.722752,4310.934002,693.816504,5753.066494,956.831729,1372.696674
2021,29127.75938,1545.613215,355.777826,1766.943618,1927.474078,6377.203096,42072.31942,6419.161029,44332.34005,10650.86046,...,41976.00831,3756.488901,3044.57364,12316.10246,3857.689742,5269.783901,578.51201,7073.612754,1134.713454,1773.920411
2022,33300.83882,1644.062829,NaN,1785.312219,3000.444231,6810.114041,41992.77278,7625.252464,53707.98008,13650.60463,...,NaN,4163.514299,3231.3513,12687.74189,3745.560367,5340.268798,543.637538,6766.481254,1456.90157,1676.821489
2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,650.272218,NaN,NaN,NaN

In [42]:
df_stack = df.set_index("Country Code")[["2002", "2003"]].stack().reset_index().rename(columns={"level_1": "Year", 0: "GDP"})

In [46]:
df_stack.pivot(index = "Country Code", columns = "Year", values = "GDP")

ValueError: Index contains duplicate entries, cannot reshape

In [37]:
df_stack.pivot(index = "Country Code", columns=["level_1"], values=0)

ValueError: Index contains duplicate entries, cannot reshape

In [27]:
df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,26940.264110,28419.264530,28449.712950,29329.081750,30918.483580,31902.809820,24008.127820,29127.759380,33300.838820,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,"141,3859554",144.342434,148.774835,157.047580,166.849791,177.769086,...,1725.332959,1554.167299,1444.003514,1625.286236,1558.307482,1507.982881,1355.805923,1545.613215,1644.062829,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,"62,36937451",62.443703,60.950364,82.021738,85.511073,105.243196,...,626.512931,566.881133,523.053012,526.140801,492.090632,497.741429,512.055098,355.777826,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,"107,0537061",112.128417,117.814663,122.370114,130.700278,137.301801,...,2248.316255,1882.264038,1648.762676,1590.277754,1735.374911,1812.446822,1688.075575,1766.943618,1785.312219,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5011.984412,3217.339244,1809.709377,2439.374441,2540.508878,2191.347764,1450.905112,1927.474078,3000.444231,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3902.530841,3520.782075,3759.472855,4009.353811,4384.188680,4416.029253,4310.934002,5269.783901,5340.268798,NaN
262,Yemen,Rep.,YEM,GDP per capita (current US$),"NY,GDP,PCAP,CD",NaN,NaN,NaN,NaN,NaN,...,1497.747941,1557.601406,1488.416269,1069.816998,893.716494,701.714869,693.816504,578.512010,543.637538,650.272218
263,South Africa,ZAF,GDP per capita (current US$),NY.GDP.PCAP.CD,"529,5619227",543.042224,560.699395,601.599951,642.688431,681.131111,...,6965.137897,6204.929901,5735.066787,6734.475153,7067.724165,6702.526617,5753.066494,7073.612754,6766.481254,NaN
264,Zambia,ZMB,GDP per capita (current US$),NY.GDP.PCAP.CD,"228,5673985",216.274674,208.562685,209.453362,236.941713,296.022427,...,1724.576220,1307.909649,1249.923143,1495.752138,1475.199883,1268.120941,956.831729,1134.713454,1456.901570,NaN
265,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,"276,6433633",279.332656,275.966139,277.532515,282.376856,294.893605,...,1407.034291,1410.329173,1421.787791,1192.107012,2269.177012,1421.868596,1372.696674,1773.920411,1676.821489,NaN